# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/chatbot_db
spring.datasource.username=root
spring.datasource.password=root@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ollama
ollama.api.url=http://localhost:11434/api/generate
ollama.model=qwen2.5:1.5b

# Safety
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
